openapi: "3.0.3"
info:
  title: "Minesweeper API"
  version: "1.0.0"
security:
  - XAuthTokenHeader: []
components:
  securitySchemes:
    XAuthTokenHeader:
      type: apiKey
      in: header
      name: X-Auth-Token
  responses:
    BadRequest:
      description: Invalid input data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: User isn't authenticated or token is invalid
  schemas:
    Credentials:
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 4
    BoardConfiguration:
      properties:
        rows:
          type: integer
          minimum: 2
          maximum: 20
        columns:
          type: integer
          minimum: 2
          maximum: 20
        mines:
          type: integer
          minimum: 1
    BoardSummary:
      properties:
        uid:
          type: string
        rows:
          type: integer
        columns:
          type: integer
        mines:
          type: integer
        isActive:
          type: boolean
        isGameOver:
          type: boolean
    BoardDetails:
      properties:
        cells:
          type: array
          items:
            type: array
            items:
              type: integer
        stringRepresentation:
          type: string
    PlayerMoveType:
      type: string
      enum: [reveal, redFlag, questionMark, clearFlag]
    Coordinates:
      properties:
        row:
          type: integer
          minimum: 0
          maximum: 20
        column:
          type: integer
          minimum: 0
          maximum: 20
    PlayerMove:
      properties:
        moveType:
          $ref: '#/components/schemas/PlayerMoveType'
        coordinates:
          $ref: '#/components/schemas/Coordinates'
    ErrorResponse:
      properties:
        error:
          properties:
            requestId:
              type: integer
              description: Number to identify the request
            message:
              type: string
              description: Description of the error
